globalThis.extAPI = typeof browser !== 'undefined' ? browser : chrome;

globalThis.CLEAN_BROWSE_CONFIG = Object.freeze({
  APP_NAME: "CleanBrowse",
  LOG_PREFIX: "[CleanBrowse]",
  LOCAL_API_BASE_URL: "http://127.0.0.1:5000",
  ANALYZE_TEXT_ROUTE: "/analyze-text",
  REPORT_EVENT_ROUTE: "/report-event",
  REPORT_UNINSTALL_ROUTE: "/report-uninstall",
  HEARTBEAT_ROUTE: "/heartbeat",
  HEARTBEAT_INTERVAL: 15000, // 15 seconds
  SAFETY_MODES: Object.freeze({
    KID: { id: "KID", label: "Kid", threshold: 0.2, description: "Maximum safety. Blocks even mildly suggestive content." },
    TEEN: { id: "TEEN", label: "Teen", threshold: 0.5, description: "Standard safety. Balanced AI filtering for adolescents." }
  }),
  DEFAULT_MODE_ID: "TEEN",
  BLOCKED_PAGE_FILENAME: "blocked.html",
  SAFE_URL_PREFIXES: Object.freeze([
    "chrome://",
    "edge://",
    "about:",
    "devtools://",
    "chrome-extension://",
    "moz-extension://"
  ]),
  LEET_CHARACTER_MAP: Object.freeze({
    "0": "o",
    "1": "i",
    "3": "e",
    "4": "a",
    "5": "s",
    "7": "t",
    "@": "a",
    "$": "s",
    "!": "i"
  }),
  CHARACTER_VARIANTS: Object.freeze({
    a: "[aA4@]",
    b: "[bB8]",
    e: "[eE3]",
    g: "[gG69]",
    i: "[iI1!|]",
    l: "[lL1|!]",
    o: "[oO0]",
    s: "[sS5$]",
    t: "[tT7+]",
    x: "[xX%*]",
    z: "[zZ2]"
  }),
  URL_BLOCK_CATEGORIES: Object.freeze({
    "adult": [
      "porn",
      "sexual",
      "erection",
      "pornographic",
      "explicit content",
      "xxx",
      "adult",
      "adult video",
      "adult site",
      "adult streaming",
      "adult subscription",
      "sex",
      "sexvideo",
      "sex tape",
      "sexvideo live",
      "sexvideo call",
      "sexvideo site",
      "sexvideo app",
      "sexvideo chat",
      "sexvideo room",
      "sexvideo live stream",
      "blowjob",
      "handjob",
      "gangbang",
      "threesome",
      "erotic video",
      "private video",
      "leaked video",
      "hidden cam",
      "nude",
      "nudity",
      "nsfw",
      "escort",
      "escort service",
      "call girl",
      "brothel",
      "paid sex",
      "sex service",
      "camgirl",
      "cam site",
      "webcamsex",
      "onlyfans",
      "strip",
      "striptease",
      "lap dance",
      "fetish",
      "bdsm",
      "domination",
      "submissive",
      "erotic",
      "seduction",
      "intimate",
      "lust",
      "pleasure",
      "hookup",
      "one night stand",
      "sugar daddy",
      "sugar baby",
      "making out",
      "foreplay",
      "climax",
      "orgasm",
      "penetration",
      "moaning",
      "arousal",
      "seducing",
      "dirty talk",
      "lewd",
      "thirst trap",
      "spicy content",
      "fanhouse",
      "fansly",
      "patreon adult",
      "private snaps",
      "premium snaps",
      "sexting",
      "dirty chat",
      "roleplay sex",
      "sportsbook",
      "real money games",
      "cash games",
      "teen patti cash",
      "lottery",
      "scratch cards",
      "vaping",
      "violent",
      "blood scene",
      "violent video",
      "testicles",
      "boobs",
      "tits",
      "ass",
      "booty",
      "pussy",
      "dick",
      "penis",
      "vagina",
      "breasts",
      "nipples",
      "genital",
      "cleavage",
      "pr0n",
      "p0rn",
      "s3x",
      "fxck",
      "fuk",
      "fck",
      "seggs",
      "sx",
      "pron",
      "po rn",
      "p orn",
      "fuck",
      "kiss"
    ],
    "violence": [
      "drugs",
      "drugs online",
      "buy drugs",
      "narcotics",
      "weed",
      "cocaine",
      "heroin",
      "mdma",
      "lsd",
      "ecstasy",
      "smoking",
      "vape",
      "vape pen",
      "cigarettes",
      "hookah",
      "ecigarette",
      "alcohol",
      "alcohol drink",
      "beer",
      "liquor",
      "drunk",
      "vodka",
      "whiskey",
      "violence",
      "gore",
      "gore video",
      "murder",
      "murder video",
      "suicide methods",
      "suicide tips",
      "self harm",
      "cutting",
      "how to die",
      "kill someone",
      "torture",
      "execution",
      "abuse",
      "kill",
      "killing"
    ],
    "gambling": [
      "gambling",
      "casino",
      "casino app",
      "gambling site",
      "online casino",
      "crypto betting",
      "bet",
      "betting",
      "betting app",
      "betting tips",
      "online betting",
      "betting odds",
      "odds",
      "wager",
      "wager money",
      "parlay",
      "spread betting",
      "live betting",
      "fantasy betting",
      "rummy cash",
      "poker",
      "blackjack",
      "roulette",
      "slots",
      "bingo",
      "jackpot",
      "jackpot win"
    ]
  }),
  TEXT_FILTER_TERMS: Object.freeze([
    "sex",
    "sexual",
    "erection",
    "erectile",
    "penile",
    "dysfunction",
    "sexvideo",
    "pornographic",
    "explicit content",
    "adult video",
    "adult site",
    "adult streaming",
    "adult subscription",
    "erotic video",
    "sex tape",
    "leaked video",
    "private video",
    "hidden cam",
    "sexvideo live",
    "sexvideo call",
    "sexvideo site",
    "sexvideo app",
    "sexvideo chat",
    "sexvideo room",
    "sexvideo live stream",
    "blowjob",
    "handjob",
    "gangbang",
    "threesome",
    "testes",
    "nude",
    "nudity",
    "porn",
    "xxx",
    "nsfw",
    "escort",
    "escort service",
    "call girl",
    "brothel",
    "massage parlor",
    "paid sex",
    "sex service",
    "fetish",
    "bdsm",
    "domination",
    "submissive",
    "erotic",
    "seduction",
    "making out",
    "foreplay",
    "climax",
    "orgasm",
    "penetration",
    "moaning",
    "arousal",
    "seducing",
    "striptease",
    "lap dance",
    "dirty talk",
    "intimate",
    "lust",
    "pleasure",
    "hookup",
    "one night stand",
    "sugar daddy",
    "sugar baby",
    "lewd",
    "thirst trap",
    "spicy content",
    "fanhouse",
    "fansly",
    "patreon adult",
    "private snaps",
    "premium snaps",
    "sexting",
    "dirty chat",
    "roleplay sex",
    "boobs",
    "tits",
    "ass",
    "booty",
    "pussy",
    "dick",
    "penis",
    "vagina",
    "breasts",
    "nipples",
    "genital",
    "cleavage",
    "violence",
    "violent",
    "gore",
    "gore video",
    "bloodshed",
    "blood scene",
    "abuse",
    "murder",
    "murder video",
    "kill",
    "killing",
    "suicide methods",
    "suicide tips",
    "self harm",
    "cutting",
    "how to die",
    "kill someone",
    "violent video",
    "torture",
    "execution",
    "gambling",
    "casino",
    "casino app",
    "gambling site",
    "online casino",
    "betting",
    "sportsbook",
    "betting tips",
    "betting app",
    "online betting",
    "betting odds",
    "odds",
    "wager",
    "wager money",
    "parlay",
    "spread betting",
    "live betting",
    "crypto betting",
    "fantasy betting",
    "real money games",
    "cash games",
    "rummy cash",
    "teen patti cash",
    "lottery",
    "scratch cards",
    "poker",
    "roulette",
    "slots",
    "drugs",
    "drugs online",
    "buy drugs",
    "narcotics",
    "weed",
    "smoking",
    "cigarettes",
    "hookah",
    "alcohol",
    "alcohol drink",
    "beer",
    "testicle",
    "testicles",
    "liquor",
    "drunk",
    "vodka",
    "whiskey",
    "vaping",
    "vape",
    "vape pen",
    "ecigarette",
    "drugs",
    "cocaine",
    "meth",
    "heroin",
    "mdma",
    "lsd",
    "ecstasy",
    "pr0n",
    "p0rn",
    "s3x",
    "fxck",
    "fuk",
    "fck",
    "seggs",
    "sx",
    "pron",
    "po rn",
    "p orn",
    "sperm",
    "cum",
    "ejaculate",
    "orgy",
    "anal",
    "vaginal",
    "fuck"
  ]),
  TEXT_SCAN_TARGET_SELECTOR: "p, span, div, h1, h2, h3, h4, h5, h6, label, section, article",
  IMAGE_SCAN_SELECTOR: "img",
  BLUR_CLASS_NAME: "kid-safe-blur"
});
